name: IaC static analysis 

on:
  workflow_call:
    inputs:
      skipped_check_ids:
        description: "Comma separated Checkov check IDs to skip"
        required: false
        type: string
    secrets:
      GITHUB_PAT:
        description: "A GitHub PAT used to initialize private submodules"
        required: true

jobs:
  iac-static-analysis:
    name: ""
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          ref: ${{ steps.load-pr.outputs.head_sha }}
          token: ${{ secrets.GITHUB_PAT }} 
      
      - name: Setup Git Config
        run: |
          git config --global \
            url."https://oauth2:${{ secrets.GITHUB_PAT }}@github.com".insteadOf https://github.com

      - name: Set check_ids to skip
        id: skipped_checks
        run: |
          SKIPPED_CHECKS="${{ inputs.skipped_check_ids }}"
          echo "::set-output name=value::${SKIPPED_CHECKS:-""}"

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true 
          framework: terraform 
          output_format: github_failed_only
          download_external_modules: true
          skip_check: ${{ steps.skipped_checks.outputs.value }}


      - name: Display Checkov results
        id: report_success
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            let message = "";

            if (${{ steps.skipped_checks.outputs.value }} != "" ) {
              message = `Check IDs ${{ steps.skipped_checks.outputs.value }} was skipped.`;
            } 

            const output = `#### Static Analysis - No issues found :white_check_mark:
            ${message}

            *Pusher: @${{ github.actor }}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Display Checkov failed results
        id: report_failures
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const output = `#### Static Analysis - Issues found :warning:
          
            <details><summary>Show Checkov results</summary>

            ${{ env.CHECKOV_RESULTS }}

            </details>

            *Pusher: @${{ github.actor }}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
