name: Terraform Fmt

on:
  workflow_call:

jobs:
  terraform-fmt:
    name: Format and Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set terraform version
        id: set-terraform-version
        run: echo "::set-output name=terraform-version::$(cat .terraform-version)"

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.terraform-version}}
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: |
          terraform fmt -recursive -check=true -write=false -diff > terraform-fmt.diff
          terraform fmt -recursive -check

      - name: Output Fmt Result
        uses: actions/github-script@v2
        if: always() && github.event_name == 'pull_request' && steps.fmt.outcome != 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const fmt_diff = fs.readFileSync("./terraform-fmt.diff").toString();
            const output = `#### Terraform Format: 

            Terraform format failed! Run \`terraform fmt -recursive\` to fix this!

            \`\`\`diff
            ${ fmt_diff }
            \`\`\`

            *Pusher: @${{ github.actor }}*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

